/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NfcBusinessCardGuideRouteImport } from './routes/nfc-business-card-guide'
import { Route as NfcBusinessCardsRouteImport } from './routes/nfc-business-cards'
import { Route as NfcCardsRouteImport } from './routes/nfc-cards'
import { Route as PressRouteImport } from './routes/press'
import { Route as TemplatesRouteImport } from './routes/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcBusinessCardGuideRoute = NfcBusinessCardGuideRouteImport.update({
  id: '/nfc-business-card-guide',
  path: '/nfc-business-card-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcBusinessCardsRoute = NfcBusinessCardsRouteImport.update({
  id: '/nfc-business-cards',
  path: '/nfc-business-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcCardsRoute = NfcCardsRouteImport.update({
  id: '/nfc-cards',
  path: '/nfc-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/nfc-business-card-guide': typeof NfcBusinessCardGuideRoute
  '/nfc-business-cards': typeof NfcBusinessCardsRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/press': typeof PressRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/nfc-business-card-guide': typeof NfcBusinessCardGuideRoute
  '/nfc-business-cards': typeof NfcBusinessCardsRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/press': typeof PressRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/nfc-business-card-guide': typeof NfcBusinessCardGuideRoute
  '/nfc-business-cards': typeof NfcBusinessCardsRoute
  '/nfc-cards': typeof NfcCardsRoute
  '/press': typeof PressRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/nfc-business-card-guide'
    | '/nfc-business-cards'
    | '/nfc-cards'
    | '/press'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/nfc-business-card-guide'
    | '/nfc-business-cards'
    | '/nfc-cards'
    | '/press'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/nfc-business-card-guide'
    | '/nfc-business-cards'
    | '/nfc-cards'
    | '/press'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  NfcBusinessCardGuideRoute: typeof NfcBusinessCardGuideRoute
  NfcBusinessCardsRoute: typeof NfcBusinessCardsRoute
  NfcCardsRoute: typeof NfcCardsRoute
  PressRoute: typeof PressRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-business-card-guide': {
      id: '/nfc-business-card-guide'
      path: '/nfc-business-card-guide'
      fullPath: '/nfc-business-card-guide'
      preLoaderRoute: typeof NfcBusinessCardGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-business-cards': {
      id: '/nfc-business-cards'
      path: '/nfc-business-cards'
      fullPath: '/nfc-business-cards'
      preLoaderRoute: typeof NfcBusinessCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-cards': {
      id: '/nfc-cards'
      path: '/nfc-cards'
      fullPath: '/nfc-cards'
      preLoaderRoute: typeof NfcCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  NfcBusinessCardGuideRoute: NfcBusinessCardGuideRoute,
  NfcBusinessCardsRoute: NfcBusinessCardsRoute,
  NfcCardsRoute: NfcCardsRoute,
  PressRoute: PressRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
